[build]
builder = "nixpacks"
buildCommand = "npm --prefix backend install"

[deploy]
startCommand = "node backend/server.js"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

[nixpacks]
install = "npm --prefix backend install"
start = "node backend/server.js"
